apiVersion: v1
kind: Service
metadata:
  name: prometheus-global
  namespace: monitoring
  annotations:
    io.cilium/global-service: "true"
    io.cilium/shared-service: "true"
    metallb.io/loadBalancerIPs: 172.18.255.45
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
