# RKE2 cluster join token: generated by Terraform, kept in Secrets Manager.
# Never committed to Git and never passed through tfvars.
resource "random_password" "rke2_token" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "rke2_token" {
  name                    = "${var.project_name}/${var.environment}/rke2-token"
  description             = "RKE2 join token for ${var.environment}"
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "rke2_token" {
  secret_id     = aws_secretsmanager_secret.rke2_token.id
  secret_string = random_password.rke2_token.result
}
