#!/usr/bin/env bash
# Usage: gen-ansible-inventory.sh <rke2-management|rke2-dev|rke2-prod>
# Sinh ansible/inventory_<stack>.yml từ Terraform output: node private IP + ProxyJump
# qua OpenVPN host. Không SSM, không public IP trên node.
set -euo pipefail

stack="${1:?stack: rke2-management|rke2-dev|rke2-prod}"
env_name="${stack#rke2-}"
repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
chdir="${repo_root}/terraform/environments/${stack}"
mgmt_chdir="${repo_root}/terraform/environments/rke2-management"
out="${repo_root}/ansible/inventory_${stack}.yml"

tf_json() { terraform -chdir="$1" output -json "$2"; }

jump_ip="$(terraform -chdir="$mgmt_chdir" output -raw openvpn_public_ip)"
jump_key="$(terraform -chdir="$mgmt_chdir" output -raw ssh_private_key_path)"
node_key="$(terraform -chdir="$chdir" output -raw ssh_private_key_path)"

masters="$(tf_json "$chdir" master_private_ips)"
workers="$(tf_json "$chdir" worker_private_ips)"

MASTERS="$masters" WORKERS="$workers" \
JUMP_IP="$jump_ip" JUMP_KEY="$jump_key" NODE_KEY="$node_key" ENV_NAME="$env_name" \
python3 - >"$out" <<'PY'
import json, os

masters = json.loads(os.environ["MASTERS"])
workers = json.loads(os.environ["WORKERS"])
jump_ip = os.environ["JUMP_IP"]
jump_key = os.environ["JUMP_KEY"]
node_key = os.environ["NODE_KEY"]
env_name = os.environ["ENV_NAME"]

proxy = (
    f'-o StrictHostKeyChecking=no -o IdentitiesOnly=yes '
    f'-o ProxyCommand="ssh -W %h:%p -i {jump_key} '
    f'-o StrictHostKeyChecking=no -o IdentitiesOnly=yes ubuntu@{jump_ip}"'
)

print(f"# Generated by scripts/rke2/gen-ansible-inventory.sh for {env_name}. Do not edit.")
print("rke2_nodes:")
print("  hosts:")
for i, ip in enumerate(masters, 1):
    print(f"    {env_name}-master-{i}:")
    print(f"      ansible_host: {ip}")
for i, ip in enumerate(workers, 1):
    print(f"    {env_name}-worker-{i}:")
    print(f"      ansible_host: {ip}")
print("  vars:")
print("    ansible_user: ubuntu")
print(f"    ansible_ssh_private_key_file: {node_key}")
print(f'    ansible_ssh_common_args: \'{proxy}\'')
PY

echo "wrote ${out}"
